# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import BullyElection_pb2 as BullyElection__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in BullyElection_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BullyElectionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Election = channel.unary_unary(
                '/BullyElection/Election',
                request_serializer=BullyElection__pb2.ElectionMessage.SerializeToString,
                response_deserializer=BullyElection__pb2.CandidateMessage.FromString,
                _registered_method=True)
        self.Leader = channel.unary_unary(
                '/BullyElection/Leader',
                request_serializer=BullyElection__pb2.LeaderMessage.SerializeToString,
                response_deserializer=BullyElection__pb2.ResponseMessage.FromString,
                _registered_method=True)
        self.Request = channel.unary_unary(
                '/BullyElection/Request',
                request_serializer=BullyElection__pb2.RequestMessage.SerializeToString,
                response_deserializer=BullyElection__pb2.ResponseMessage.FromString,
                _registered_method=True)


class BullyElectionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Election(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Leader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Request(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BullyElectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Election': grpc.unary_unary_rpc_method_handler(
                    servicer.Election,
                    request_deserializer=BullyElection__pb2.ElectionMessage.FromString,
                    response_serializer=BullyElection__pb2.CandidateMessage.SerializeToString,
            ),
            'Leader': grpc.unary_unary_rpc_method_handler(
                    servicer.Leader,
                    request_deserializer=BullyElection__pb2.LeaderMessage.FromString,
                    response_serializer=BullyElection__pb2.ResponseMessage.SerializeToString,
            ),
            'Request': grpc.unary_unary_rpc_method_handler(
                    servicer.Request,
                    request_deserializer=BullyElection__pb2.RequestMessage.FromString,
                    response_serializer=BullyElection__pb2.ResponseMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BullyElection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('BullyElection', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BullyElection(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Election(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BullyElection/Election',
            BullyElection__pb2.ElectionMessage.SerializeToString,
            BullyElection__pb2.CandidateMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Leader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BullyElection/Leader',
            BullyElection__pb2.LeaderMessage.SerializeToString,
            BullyElection__pb2.ResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Request(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BullyElection/Request',
            BullyElection__pb2.RequestMessage.SerializeToString,
            BullyElection__pb2.ResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
