# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BullyElection.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BullyElection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x42ullyElection.proto\"\x10\n\x0eRequestMessage\"#\n\x0fResponseMessage\x12\x10\n\x08priority\x18\x01 \x01(\x05\"\x11\n\x0f\x45lectionMessage\"$\n\x10\x43\x61ndidateMessage\x12\x10\n\x08priority\x18\x01 \x01(\x05\"\"\n\rLeaderMessage\x12\x11\n\tleader_id\x18\x01 \x01(\t2\x9a\x01\n\rBullyElection\x12/\n\x08\x45lection\x12\x10.ElectionMessage\x1a\x11.CandidateMessage\x12*\n\x06Leader\x12\x0e.LeaderMessage\x1a\x10.ResponseMessage\x12,\n\x07Request\x12\x0f.RequestMessage\x1a\x10.ResponseMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BullyElection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTMESSAGE']._serialized_start=23
  _globals['_REQUESTMESSAGE']._serialized_end=39
  _globals['_RESPONSEMESSAGE']._serialized_start=41
  _globals['_RESPONSEMESSAGE']._serialized_end=76
  _globals['_ELECTIONMESSAGE']._serialized_start=78
  _globals['_ELECTIONMESSAGE']._serialized_end=95
  _globals['_CANDIDATEMESSAGE']._serialized_start=97
  _globals['_CANDIDATEMESSAGE']._serialized_end=133
  _globals['_LEADERMESSAGE']._serialized_start=135
  _globals['_LEADERMESSAGE']._serialized_end=169
  _globals['_BULLYELECTION']._serialized_start=172
  _globals['_BULLYELECTION']._serialized_end=326
# @@protoc_insertion_point(module_scope)
