# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: replication.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'replication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11replication.proto\x12\x0breplication\x1a\x1bgoogle/protobuf/empty.proto\"o\n\x0bVectorClock\x12\x32\n\x05\x63lock\x18\x01 \x03(\x0b\x32#.replication.VectorClock.ClockEntry\x1a,\n\nClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\"i\n\x0b\x43hatMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\x12\n\n\x02ts\x18\x04 \x01(\x03\x12$\n\x02vc\x18\x05 \x01(\x0b\x32\x18.replication.VectorClock\"N\n\x10ReplicateRequest\x12%\n\x03msg\x18\x01 \x01(\x0b\x32\x18.replication.ChatMessage\x12\x13\n\x0borigin_node\x18\x02 \x01(\t\"/\n\x11ReplicateResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t2\x9d\x01\n\x0bReplication\x12J\n\tReplicate\x12\x1d.replication.ReplicateRequest\x1a\x1e.replication.ReplicateResponse\x12\x42\n\x0c\x46\x65tchMissing\x12\x16.google.protobuf.Empty\x1a\x18.replication.ChatMessage0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'replication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTORCLOCK_CLOCKENTRY']._loaded_options = None
  _globals['_VECTORCLOCK_CLOCKENTRY']._serialized_options = b'8\001'
  _globals['_VECTORCLOCK']._serialized_start=63
  _globals['_VECTORCLOCK']._serialized_end=174
  _globals['_VECTORCLOCK_CLOCKENTRY']._serialized_start=130
  _globals['_VECTORCLOCK_CLOCKENTRY']._serialized_end=174
  _globals['_CHATMESSAGE']._serialized_start=176
  _globals['_CHATMESSAGE']._serialized_end=281
  _globals['_REPLICATEREQUEST']._serialized_start=283
  _globals['_REPLICATEREQUEST']._serialized_end=361
  _globals['_REPLICATERESPONSE']._serialized_start=363
  _globals['_REPLICATERESPONSE']._serialized_end=410
  _globals['_REPLICATION']._serialized_start=413
  _globals['_REPLICATION']._serialized_end=570
# @@protoc_insertion_point(module_scope)
