# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ChatServer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ChatServer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x43hatServer.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd0\x01\n\x0b\x43hatMessage\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x14\n\x0crecipient_id\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x03(\t\x12)\n\x07v_clock\x18\x04 \x03(\x0b\x32\x18.ChatMessage.VClockEntry\x12-\n\tdate_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a-\n\x0bVClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\x81\x02\n\x12\x43hatServerResponse\x12/\n\x0bstatus_code\x18\x01 \x01(\x0e\x32\x1a.ChatServerResponse.status\x12\x0f\n\x07payload\x18\x02 \x03(\t\x12\x30\n\x07v_clock\x18\x03 \x03(\x0b\x32\x1f.ChatServerResponse.VClockEntry\x12-\n\tdate_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a-\n\x0bVClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\x19\n\x06status\x12\x06\n\x02OK\x10\x00\x12\x07\n\x03\x45RR\x10\x01\x32:\n\nChatServer\x12,\n\x07\x46orward\x12\x0c.ChatMessage\x1a\x13.ChatServerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChatServer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATMESSAGE_VCLOCKENTRY']._loaded_options = None
  _globals['_CHATMESSAGE_VCLOCKENTRY']._serialized_options = b'8\001'
  _globals['_CHATSERVERRESPONSE_VCLOCKENTRY']._loaded_options = None
  _globals['_CHATSERVERRESPONSE_VCLOCKENTRY']._serialized_options = b'8\001'
  _globals['_CHATMESSAGE']._serialized_start=54
  _globals['_CHATMESSAGE']._serialized_end=262
  _globals['_CHATMESSAGE_VCLOCKENTRY']._serialized_start=217
  _globals['_CHATMESSAGE_VCLOCKENTRY']._serialized_end=262
  _globals['_CHATSERVERRESPONSE']._serialized_start=265
  _globals['_CHATSERVERRESPONSE']._serialized_end=522
  _globals['_CHATSERVERRESPONSE_VCLOCKENTRY']._serialized_start=217
  _globals['_CHATSERVERRESPONSE_VCLOCKENTRY']._serialized_end=262
  _globals['_CHATSERVERRESPONSE_STATUS']._serialized_start=497
  _globals['_CHATSERVERRESPONSE_STATUS']._serialized_end=522
  _globals['_CHATSERVER']._serialized_start=524
  _globals['_CHATSERVER']._serialized_end=582
# @@protoc_insertion_point(module_scope)
